Parameters:
  EC2InstanceType:
    Default: m4.large
    Description: EC2 instance type on which IDE runs
    Type: String
  AutoHibernateTimeout:
    Default: 30
    Description: How many minutes idle before shutting down the IDE
    Type: Number 
  Cloud9Name:
    Default: AppSyncWorkshop
    Type: String
Resources:
  IDE:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Repositories:
      - RepositoryUrl: https://github.com/lucasschejtman/resttogql-workshop
        PathComponent: resttogql-workshop
      Description: Cloud9 IDE
      AutomaticStopTimeMinutes:
        Ref: AutoHibernateTimeout
      InstanceType:
        Ref: EC2InstanceType
      Name:
        Ref: Cloud9Name